[package]
name = "dailygo-ffi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "dailygo_ffi"

[dependencies]
dailygo-core = { path = "../dailygo-core" }
uniffi = { workspace = true, features = ["cli"] }
thiserror = { workspace = true }

[build-dependencies]
uniffi_build = { workspace = true }
